name = "panel" # todo
main = "_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "panel.cloudproxyip.my.id.winner.cloudproxyip.my.id"
custom_domain = true
